site_name: Quant Freedom

repo_url: https://github.com/QuantFreedom1022/quantfreedom
repo_name: Quant Freedom

theme:
  name: material
  # @ts-ignore
  include_search_page: false
  search_index_only: true
  language: en
  palette:
    scheme: default
    primary: teal
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.share
  logo: assets/chart.png
  favicon: /assets/logo/favicon.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QuantFreedom1022/quantfreedom
    - icon: fontawesome/brands/discord
      link: https://discord.gg/f3JTmPGBfe
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCSulhidOZtE5QVULIwCLzDg

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      extend_pygments_lang:
        - name: pycon3
          lang: pycon
          options:
            python3: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: QuantFreedom1022
      repo: quantfreedom
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - gen-files:
      scripts:
        - gen_ref_pages.py
  - open-in-new-tab
  - autorefs
  - tags
  - literate-nav:
      nav_file: SUMMARY.md
  - minify:
      minify_html: true
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      enable_inventory: true
      default_handler: python
      handlers:
        python:
          paths: [..]
          options:
            show_source: false
            line_length: 1
            separate_signature: true
            docstring_style: numpy
            docstring_section_style: list

nav:
  - Getting Started:
    - index.md
    - Installation: getting-started/install.md
    - Release Notes: getting-started/releasenotes.md
  - Coding Tutorials:
      - coding_tus/index.md
      - Numpy:
          - coding_tus/numpy/broadcasting.md
          - coding_tus/numpy/logical.md
          - coding_tus/numpy/random.md
      - Pandas DataFrame:
          - coding_tus/pandas_dataframe/dataframe.md
      - Pandas Functions:
          - coding_tus/pandas_functions/multiindex.md
          - coding_tus/pandas_functions/indexing.md
  - API: api/*
